# Generated by Django 4.2.7 on 2023-11-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medical_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Sex', models.CharField(max_length=400)),
                ('Age', models.CharField(max_length=400)),
                ('Marital_status', models.CharField(max_length=400)),
                ('Address', models.CharField(max_length=400)),
                ('Medical_history', models.CharField(max_length=100000000000000000000000)),
                ('Recomendation', models.CharField(max_length=9000000000000000000000000)),
                ('Prescriptions', models.CharField(max_length=90000000000000000000)),
                ('Doctors_name', models.CharField(max_length=200)),
            ],
        ),
    ]
